# Generated by Django 6.1 on 2026-08-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ACTA', 'Acta'), ('CUENTA', 'Estado de cuenta'), ('COMUNICADO', 'Comunicado'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
